apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: gohttp
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: gohttp
  service:
    name: gohttp
    port: 3000
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
